apiVersion: v1               
kind: Namespace              
metadata:                    
  name: app1-dev
  Labels:
    app: app1
    env: dev
---
apiVersion: v1                
kind: Pod                     
metadata:                     
  name: app1-pod-1
  labels:
    env: dev
    app: app1
  namespace: app1-pod-1
spec:                       
  containers:
  - image: nginx:latest              
    name: nginx   
    ports:            
    - containerPort: 80      
      protocol: TCP