apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 80    # Container Port

# By default type will be Cluster IP