apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:               # specification/contents for replicationcontroller
  replicas: 6
  selector:         # label selector for replicationcontroller
    app: nginx
  template:         # pod template
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:           # spec for containers
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

# akms - api version, kind, metadata, specificaiton