apiVersion: v1               
kind: Namespace              
metadata:                    
  name: applicaiton

---

apiVersion: v1                
kind: Pod                     
metadata:                     
  name: apachepod
  labels:
    app: apache
  namespace: applicaiton
spec:                       
  containers:
  - image: paketobuildpacks/httpd:0.7
    name: apache-container
    ports:
    - containerPort: 80
